- name: install software-properties-common
  package:
    name:  software-properties-common
    state: present
  tags:
    - podman
    - install

- name: add source debian
  block:
    - copy:
        dest:    "/etc/apt/sources.list.d/devel-kubic-libcontainers-stable.list"
        content: |
             deb {{ package_source[ansible_distribution]['repo'] }} /
    - apt_key:
        url:   "{{ package_source[ansible_distribution]['key'] }}"
        state: present
  tags:
    - podman
    - install

- name: refresh apt
  apt:
    update_cache: true
  tags:
    - podman
    - install

- name: install podman
  package:
    name:  podman
    state: present
  tags:
    - podman
    - install