---
- name: install software-properties-common
  package:
    name:
      - software-properties-common
      - gpg
    state: present
  tags:
    - podman
    - install

- name: add apt source
  copy:
    dest:    "/etc/apt/sources.list.d/devel-kubic-libcontainers-stable.list"
    content: |
             deb {{ package_source[ansible_distribution]['repo'] }} /
  tags:
    - podman
    - install

- name: add apt key
  apt_key:
    url:   "{{ package_source[ansible_distribution]['key'] }}"
    state: present
  when: ansible_distribution == "Debian" and ansible_distribution_release == "buster"
  tags:
    - podman
    - install

- name: refresh apt
  apt:
    update_cache: true
  tags:
    - podman
    - install

- name: install libseccomp from backports
  apt:
    state:           latest
    name:            libseccomp2
    default_release: buster-backports
  tags:
    - podman
    - install

- name: install cri-o-runc
  package:
    name:
      - cri-o-runc
    state: latest
  tags:
    - podman
    - install