- name: add golang ppa
  apt_repository:
    repo: 'ppa:longsleep/golang-backports'
    state: present
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04"

- apt:
    update_cache: yes
    cache_valid_time: 86400 #One day
  tags:
    - podman
    - install


- name: install common build-time dependencies
  block:
    - package:
        name: '{{ item }}'
        state: present
      with_items:
        - btrfs-tools
        - git
        - golang-go
        - go-md2man
        - iptables
        - libassuan-dev
#        - libbtrfs-dev # TODO: figure out if needed and/or what replaces it below ubuntu 18.10+
        - libc6-dev
        - libdevmapper-dev
        - libglib2.0-dev
        - libgpg-error-dev
        - libprotobuf-dev
#        - libprotobuf-c0-dev
        - libprotobuf-c1-dev
        - libseccomp-dev
        - libselinux1-dev
        - libsystemd-dev
        - pkg-config
        - runc
        - uidmap
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
    - package:
        name: '{{ item }}'
        state: present
      with_items:
        - libgpgme11-dev
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04"
    - package:
        name: '{{ item }}'
        state: present
      with_items:
        - libbtrfs-dev
        - libgpgme-dev
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "18.04"
  tags:
    - podman
    - install

- name: checkout required repositories
  block:
    - name: checkout podman repo
      become: yes
      git:
        repo: '{{ install_podman_git_repo }}'
        dest: '/home/{{ ansible_user }}/libpod/'
        version: '{{ install_podman_version }}'

    - name: checkout conmon repo
      become: yes
      git:
        repo: '{{ install_conmon_git_repo }}'
        dest: '/home/{{ ansible_user }}/conmon/'
        version: '{{ install_conmon_version }}'

    - name: checkout containernetworking_plugins repo
      become: yes
      git:
        repo: '{{ install_containernetworking_plugins_git_repo }}'
        dest: '/home/{{ ansible_user }}/containernetworking_plugins/'
        version: '{{ install_containernetworking_plugins_version }}'

  tags:
    - podman
    - install
    - git

- name: build and install required dependencies
  block:
    - name: build and install podman
      become: yes
      shell: make install
      args:
        executable: /bin/bash
        chdir: '/home/{{ ansible_user }}/libpod/'
        creates: /usr/local/bin/podman

    - name: build and install conmon
      become: yes
      shell: make install
      args:
        executable: /bin/bash
        chdir: '/home/{{ ansible_user }}/conmon/'
        creates: /usr/local/bin/conmon

    - name: build and install containernetworking-plugins
      become: yes
      shell: ./build_linux.sh
      args:
        executable: /bin/bash
        chdir: '/home/{{ ansible_user }}/containernetworking_plugins/'
        creates: '/home/{{ ansible_user }}/containernetworking_plugins/bin/loopback'

    - name: create cni plugin dir
      file:
        dest: /usr/libexec/cni
        state: directory
        owner: root
        group: root

    - name: copy built cni plugins to the correct dir
      synchronize:
        src: '/home/{{ ansible_user }}/containernetworking_plugins/bin/'
        dest: '/usr/libexec/cni/'
      delegate_to: "{{ inventory_hostname }}"

  tags:
    - podman
    - install
    - build


