---
- name: install podman
  include_tasks: install_package.yml
  tags:
    - podman
    - install

- name:   set up /etc/containers
  file:
    name:  /etc/containers
    owner: root
    group: root
    state: directory
  become: yes
  tags:
    - podman
    - configure

- name: set up policy.json
  copy:
    dest:    /etc/containers/policy.json
    content: "{{ containers_policy | to_nice_json }}"
  tags:
    - podman
    - configure

- name: set up registries.conf - v1
  template:
    src:  templates/registries.conf.j2
    dest: /etc/containers/registries.conf
  when: registries and not registries_toml
  tags:
    - podman
    - configure

- name: set up registries.conf - v2
  template:
    src:  templates/registries.toml.j2
    dest: /etc/containers/registries.conf
  when:  registries_toml and not registries
  tags:
    - podman
    - configure

- name: fail when both registries and registries_toml are not empty
  fail:
    msg: "Set either V1 or V2 config."
  when: registries and registries_toml
  tags:
    - podman
    - configure

- name: set up storage.conf
  template:
    src:  templates/storage.conf.j2
    dest: /etc/containers/storage.conf
  tags:
    - podman
    - configure

- name: set up containers.conf
  template:
    src:  templates/containers.conf.j2
    dest: /etc/containers/containers.conf
  tags:
    - podman
    - configure


- name:       set up cni networking configs
  copy:
    dest:    "/etc/cni/net.d/{{ item.filename }}.conflist"
    content: "{{ item.data | to_nice_json }}"
  with_items: "{{ cni_networking }}"
  tags:
    - podman
    - configure

- name: set up required dir.
  file:
    path:  "{{ storage_root }}"
    owner: root
    group: root
    state: directory
  tags:
    - podman
    - configure