---
- name:   Converge
  hosts:  all
  become: yes
  roles:
    - role: podman
  tasks:
    - name: install curl
      package:
        name: curl
        state: present
  vars:
    registries:
      - prefix: docker.io
      - prefix: k8s.gcr.io
